import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib";
import { env } from "../config/env.js";

/**
 * Certificate of Completion — a self-contained PDF documenting the signing event for evidentiary
 * purposes: document identity + hashes, each signer's identity/authentication/IP, and the full
 * timestamped event timeline. Designed to be appended to the signed PDF and stored in Salesforce.
 */

export interface CertificateSigner {
  name: string;
  email: string;
  entityLabel?: string | null;
  authMethod: string;
  consentedAt?: Date | null;
  consentIp?: string | null;
  signedAt?: Date | null;
}

export interface CertificateEvent {
  occurredAt: Date;
  eventType: string;
  signerName?: string | null;
  ipAddress?: string | null;
}

export interface CertificateInput {
  documentName: string;
  requestId: string;
  status: string;
  docHashOriginal?: string | null;
  docHashFinal?: string | null;
  createdAt: Date;
  sentAt?: Date | null;
  completedAt?: Date | null;
  signers: CertificateSigner[];
  events: CertificateEvent[];
}

const PAGE = { w: 612, h: 792 };
const MARGIN = 54;
const LINE = 14;

function iso(d?: Date | null): string {
  return d ? new Date(d).toISOString() : "—";
}

function authLabel(method: string): string {
  switch (method) {
    case "EMAIL_LINK":
      return "Email link (single-use tokenized URL)";
    case "EMAIL_OTP":
      return "Email one-time passcode";
    case "SMS_OTP":
      return "SMS one-time passcode";
    default:
      return method;
  }
}

/** A tiny cursor-based text writer that paginates automatically. */
class Writer {
  private doc!: PDFDocument;
  private font!: PDFFont;
  private bold!: PDFFont;
  private page!: PDFPage;
  private y = 0;
  private readonly brand = rgb(0.063, 0.725, 0.506); // emerald ~ #10b981

  async init(): Promise<void> {
    this.doc = await PDFDocument.create();
    this.font = await this.doc.embedFont(StandardFonts.Helvetica);
    this.bold = await this.doc.embedFont(StandardFonts.HelveticaBold);
    this.newPage();
  }

  private newPage(): void {
    this.page = this.doc.addPage([PAGE.w, PAGE.h]);
    this.y = PAGE.h - MARGIN;
  }

  private ensure(space: number): void {
    if (this.y - space < MARGIN) this.newPage();
  }

  gap(h = LINE / 2): void {
    this.y -= h;
  }

  rule(): void {
    this.ensure(LINE);
    this.page.drawLine({
      start: { x: MARGIN, y: this.y },
      end: { x: PAGE.w - MARGIN, y: this.y },
      thickness: 0.5,
      color: rgb(0.85, 0.88, 0.9),
    });
    this.y -= LINE;
  }

  heading(text: string): void {
    this.ensure(LINE * 2);
    this.page.drawText(text, { x: MARGIN, y: this.y, size: 12, font: this.bold, color: this.brand });
    this.y -= LINE * 1.4;
  }

  title(text: string): void {
    this.ensure(LINE * 3);
    this.page.drawText(text, { x: MARGIN, y: this.y, size: 20, font: this.bold, color: rgb(0.06, 0.09, 0.16) });
    this.y -= LINE * 1.6;
  }

  /** Label + value on one line, value wrapped/truncated to fit. */
  kv(label: string, value: string): void {
    this.ensure(LINE);
    this.page.drawText(label, { x: MARGIN, y: this.y, size: 9, font: this.bold, color: rgb(0.4, 0.45, 0.5) });
    const labelW = 130;
    const maxW = PAGE.w - MARGIN - (MARGIN + labelW);
    const text = this.fit(value, this.font, 10, maxW);
    this.page.drawText(text, { x: MARGIN + labelW, y: this.y, size: 10, font: this.font, color: rgb(0.1, 0.12, 0.16) });
    this.y -= LINE;
  }

  line(text: string, size = 9.5): void {
    this.ensure(LINE);
    this.page.drawText(this.fit(text, this.font, size, PAGE.w - MARGIN * 2), {
      x: MARGIN,
      y: this.y,
      size,
      font: this.font,
      color: rgb(0.25, 0.28, 0.33),
    });
    this.y -= LINE * 0.95;
  }

  private fit(text: string, font: PDFFont, size: number, maxW: number): string {
    if (font.widthOfTextAtSize(text, size) <= maxW) return text;
    let t = text;
    while (t.length > 1 && font.widthOfTextAtSize(t + "…", size) > maxW) t = t.slice(0, -1);
    return t + "…";
  }

  async save(): Promise<Buffer> {
    return Buffer.from(await this.doc.save());
  }
}

export async function buildCertificate(input: CertificateInput): Promise<Buffer> {
  const w = new Writer();
  await w.init();

  w.title("Certificate of Completion");
  w.line(`Generated by ${env.BRAND_NAME} — ${iso(new Date())}`);
  w.rule();

  w.heading("Document");
  w.kv("Document name", input.documentName);
  w.kv("Request ID", input.requestId);
  w.kv("Status", input.status);
  w.kv("Original SHA-256", input.docHashOriginal ?? "—");
  w.kv("Final SHA-256", input.docHashFinal ?? "—");
  w.kv("Created (UTC)", iso(input.createdAt));
  w.kv("Sent (UTC)", iso(input.sentAt));
  w.kv("Completed (UTC)", iso(input.completedAt));
  w.gap();

  w.heading(`Signers (${input.signers.length})`);
  for (const s of input.signers) {
    w.kv("Name", s.entityLabel ? `${s.name}  ·  ${s.entityLabel}` : s.name);
    w.kv("Email", s.email);
    w.kv("Authentication", authLabel(s.authMethod));
    w.kv("Consented (UTC)", `${iso(s.consentedAt)}${s.consentIp ? `   IP ${s.consentIp}` : ""}`);
    w.kv("Signed (UTC)", iso(s.signedAt));
    w.gap();
  }

  w.rule();
  w.heading("Event timeline");
  for (const e of input.events) {
    const who = e.signerName ? ` — ${e.signerName}` : "";
    const ip = e.ipAddress ? `  (IP ${e.ipAddress})` : "";
    w.line(`${iso(e.occurredAt)}   ${e.eventType}${who}${ip}`);
  }

  w.gap();
  w.rule();
  w.line(
    `${env.BRAND_NAME} provides electronic-signature features aligned with the U.S. ESIGN Act and ` +
      `UETA. This certificate is evidence of the signing process and is not legal advice.`,
    8.5,
  );

  return w.save();
}
